_wandb:
    value:
        cli_version: 0.22.3
        e:
            5n2qmrjr83ty7cnz5bs8jrcpied2flu6:
                codePath: src\model.py
                codePathLocal: src\model.py
                cpu_count: 10
                cpu_count_logical: 16
                cudaVersion: "13.0"
                disk:
                    /:
                        total: "1023306362880"
                        used: "919258050560"
                email: pabloiribarren2003@gmail.com
                executable: C:\Users\Pablo\Documents\GitHub\data-science-job-market-spain\venv\Scripts\python.exe
                git:
                    commit: 8d3a044288f090aa393f1d018f1711842c352885
                    remote: https://github.com/pablooiiribarren/data-science-job-market-spain.git
                gpu: NVIDIA GeForce RTX 4070 Laptop GPU
                gpu_count: 1
                gpu_nvidia:
                    - architecture: Ada
                      cudaCores: 4608
                      memoryTotal: "8585740288"
                      name: NVIDIA GeForce RTX 4070 Laptop GPU
                      uuid: GPU-72a18d57-1215-b621-317c-a835ca18675d
                host: W11Pablo
                memory:
                    total: "33965981696"
                os: Windows-10-10.0.26200-SP0
                program: C:\Users\Pablo\Documents\GitHub\data-science-job-market-spain\src\model.py
                python: CPython 3.11.9
                root: C:\Users\Pablo\Documents\GitHub\data-science-job-market-spain
                startedAt: "2025-11-01T10:17:18.026119Z"
                writerId: 5n2qmrjr83ty7cnz5bs8jrcpied2flu6
        m: []
        python_version: 3.11.9
        t:
            "1":
                - 5
                - 53
                - 105
            "2":
                - 5
                - 53
                - 105
            "3":
                - 16
            "4": 3.11.9
            "5": 0.22.3
            "8":
                - 3
            "12": 0.22.3
            "13": windows-amd64
author:
    value: Pablo
dataset:
    value: jobs_cleaned.csv
framework:
    value: scikit-learn
model_version:
    value: "1.0"
